feat: Добавить сервис статистики
PetrVladimirovich/spending-time-together pull request #3
Opened 2023-04-20 22:38 UTC by PetrVladimirovich

2023-04-21 07:38 UTC, krylov-sergey-sergeevich requested changes
Привет

1) Логи давай переведем на англ
2) И пару заметок поправим

Буду ждать с правками =)

2023-04-21 07:38 UTC, krylov-sergey-sergeevich commented on stats/stat-server/src/main/java/ru/practicum/controller/StatsController.java
> +    @ResponseStatus(HttpStatus.CREATED)
разве у post запросов этот статус не по умолчанию?

2023-04-21 07:38 UTC, krylov-sergey-sergeevich commented on stats/stat-server/src/main/java/ru/practicum/controller/StatsController.java
> +        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
на каждый запрос создаем форматтер - зачем? если можно вынести в утилитный класс

2023-04-21 07:38 UTC, krylov-sergey-sergeevich commented on stats/stat-server/src/main/java/ru/practicum/mapper/StatMapper.java
> +    @Mapping(target = "timestamp", dateFormat = "yyyy-MM-dd HH:mm:ss")
**Можно лучше:** Паттерн  "yyyy-MM-dd HH:mm:ss" лучше вынести в класс Constants

2023-04-21 07:38 UTC, krylov-sergey-sergeevich commented on stats/stat-server/src/main/resources/schema.sql
> +DROP TABLE IF EXISTS stats;
Не обязательно исправлять, но можно еще так (можно иметь ввиду):
```
CREATE TABLE IF NOT EXISTS apps (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(150) NOT NULL,
  CONSTRAINT pk_aps PRIMARY KEY (id),
  CONSTRAINT UQ_APPS_NAME UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS endpoint_hit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  app_id BIGINT NOT NULL,
  uri VARCHAR(2048),
  ip VARCHAR(15) NOT NULL,
  ts TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  CONSTRAINT pk_endpoint_hit PRIMARY KEY (id),
  CONSTRAINT FK_ENDPOINT_HIT_ON_APP FOREIGN KEY (app_id) REFERENCES apps (id)
);
```

2023-04-22 03:06 UTC, PetrVladimirovich commented on stats/stat-server/src/main/java/ru/practicum/controller/StatsController.java
> +    @ResponseStatus(HttpStatus.CREATED)
вообщем без этого статуса дважды на GitHub запускал и дважды проверка 360 минут и отмена ставишь статус и все за 2 минуты проходит локально что с ним что без норм=(

2023-04-23 08:46 UTC, krylov-sergey-sergeevich approved these changes
Привет, все ок - зачет!

2023-04-26 15:11 UTC, merged