feat: Добавить Кастомный Функционал
PetrVladimirovich/spending-time-together pull request #6
Opened 2023-05-02 18:09 UTC by PetrVladimirovich

2023-05-03 06:55 UTC, krylov-sergey-sergeevich requested changes
Привет, выглядит как то местами переусложнено, давай обсудим по вопросам и далее посмотрим.

2023-05-03 06:55 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    @Formula("(select count(r.id) from requests r where r.event_id = id and r.status = 'CONFIRMED')")
Почему тут используем формулу? А не через запросы или другим способом

2023-05-03 06:55 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    @Formula("(select count(b.id) - count(c.id) from event_likes a " +
Почему тут используем формулу?

2023-05-03 06:55 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/model/ReactionOnEvent.java
> +    public enum ReactionStatus {
Рекомендую выносить в отдельный класс

2023-05-03 06:55 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/repository/UserRepository.java
> +    interface UserRating {
Почему интерфейс тут?

2023-05-03 06:55 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/service/EventService.java
> +    <T extends UpdateEventRequestDto> EventWithReactionFullDto updateEvent(Long userId, Long eventId, T dto);
Как то не переусложнено?

2023-05-03 14:02 UTC, PetrVladimirovich commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    @Formula("(select count(r.id) from requests r where r.event_id = id and r.status = 'CONFIRMED')")
Эксперименты, книгу читаю по JPA Hibernate =)

2023-05-03 14:07 UTC, PetrVladimirovich commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    @Formula("(select count(r.id) from requests r where r.event_id = id and r.status = 'CONFIRMED')")
ну и типо написано что через эту аннотацию можно поля в классе заполнять с помощью расчета из других полей=)

2023-05-04 07:34 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/service/EventService.java
> +    <T extends UpdateEventRequestDto> EventWithReactionFullDto updateEvent(Long userId, Long eventId, T dto);
Без понятия, надо смотреть ошибки и изучать)

2023-05-04 07:41 UTC, krylov-sergey-sergeevich commented on main-service/src/main/java/ru/practicum/ewm/model/Event.java
> +    @Formula("(select count(r.id) from requests r where r.event_id = id and r.status = 'CONFIRMED')")
Вроде бы это не очень эффективно, эта формула же в БД идет если я правильно понимаю

2023-05-04 07:42 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу некоторые правки - в целом для зачета тут достаточно =)

2023-05-04 15:17 UTC, merged